from typing import Literal, assert_never

type FeatureSpace = Literal[
    "known_count_flat",
    "raw_flat",
    "known_and_price_flat",
]


def get_feature_list(
    feature_space: FeatureSpace,
) -> list[str]:
    match feature_space:
        case "known_count_flat":
            return known_count
        case "raw_flat":
            return raw_all
        case "known_and_price_flat":
            return known_count + self_count + last_price
        case _:
            assert_never()


known_count = [
    "per_suit.Spade.known_count",
    "per_suit.Club.known_count",
    "per_suit.Heart.known_count",
    "per_suit.Diamond.known_count",
]
self_count = [
    "per_suit.Spade.self_position",
    "per_suit.Club.self_position",
    "per_suit.Heart.self_position",
    "per_suit.Diamond.self_position",
]

last_price = [
    "per_suit.Spade.last_price",
    "per_suit.Club.last_price",
    "per_suit.Heart.last_price",
    "per_suit.Diamond.last_price",
]
raw_all = [
    "time",
    "remaining_time",
    "remaining_time_fraction",
    "cash",
    "per_suit.Spade.last_price",
    "per_suit.Spade.volume",
    "per_suit.Spade.self_position",
    "per_suit.Spade.known_count",
    "per_suit.Spade.self_trade_summary.buy_quantity",
    "per_suit.Spade.self_trade_summary.buy_consideration",
    "per_suit.Spade.self_trade_summary.sell_quantity",
    "per_suit.Spade.self_trade_summary.sell_consideration",
    "per_suit.Spade.self_trade_summary.min_net_quantity_change",
    "per_suit.Spade.other_trade_summaries.item_0.buy_quantity",
    "per_suit.Spade.other_trade_summaries.item_0.buy_consideration",
    "per_suit.Spade.other_trade_summaries.item_0.sell_quantity",
    "per_suit.Spade.other_trade_summaries.item_0.sell_consideration",
    "per_suit.Spade.other_trade_summaries.item_0.min_net_quantity_change",
    "per_suit.Spade.other_trade_summaries.item_1.buy_quantity",
    "per_suit.Spade.other_trade_summaries.item_1.buy_consideration",
    "per_suit.Spade.other_trade_summaries.item_1.sell_quantity",
    "per_suit.Spade.other_trade_summaries.item_1.sell_consideration",
    "per_suit.Spade.other_trade_summaries.item_1.min_net_quantity_change",
    "per_suit.Spade.other_trade_summaries.item_2.buy_quantity",
    "per_suit.Spade.other_trade_summaries.item_2.buy_consideration",
    "per_suit.Spade.other_trade_summaries.item_2.sell_quantity",
    "per_suit.Spade.other_trade_summaries.item_2.sell_consideration",
    "per_suit.Spade.other_trade_summaries.item_2.min_net_quantity_change",
    "per_suit.Spade.other_trade_summaries.item_3.buy_quantity",
    "per_suit.Spade.other_trade_summaries.item_3.buy_consideration",
    "per_suit.Spade.other_trade_summaries.item_3.sell_quantity",
    "per_suit.Spade.other_trade_summaries.item_3.sell_consideration",
    "per_suit.Spade.other_trade_summaries.item_3.min_net_quantity_change",
    "per_suit.Spade.market_quote.bid.price",
    "per_suit.Spade.market_quote.bid.quantity",
    "per_suit.Spade.market_quote.ask.price",
    "per_suit.Spade.market_quote.ask.quantity",
    "per_suit.Club.last_price",
    "per_suit.Club.volume",
    "per_suit.Club.self_position",
    "per_suit.Club.known_count",
    "per_suit.Club.self_trade_summary.buy_quantity",
    "per_suit.Club.self_trade_summary.buy_consideration",
    "per_suit.Club.self_trade_summary.sell_quantity",
    "per_suit.Club.self_trade_summary.sell_consideration",
    "per_suit.Club.self_trade_summary.min_net_quantity_change",
    "per_suit.Club.other_trade_summaries.item_0.buy_quantity",
    "per_suit.Club.other_trade_summaries.item_0.buy_consideration",
    "per_suit.Club.other_trade_summaries.item_0.sell_quantity",
    "per_suit.Club.other_trade_summaries.item_0.sell_consideration",
    "per_suit.Club.other_trade_summaries.item_0.min_net_quantity_change",
    "per_suit.Club.other_trade_summaries.item_1.buy_quantity",
    "per_suit.Club.other_trade_summaries.item_1.buy_consideration",
    "per_suit.Club.other_trade_summaries.item_1.sell_quantity",
    "per_suit.Club.other_trade_summaries.item_1.sell_consideration",
    "per_suit.Club.other_trade_summaries.item_1.min_net_quantity_change",
    "per_suit.Club.other_trade_summaries.item_2.buy_quantity",
    "per_suit.Club.other_trade_summaries.item_2.buy_consideration",
    "per_suit.Club.other_trade_summaries.item_2.sell_quantity",
    "per_suit.Club.other_trade_summaries.item_2.sell_consideration",
    "per_suit.Club.other_trade_summaries.item_2.min_net_quantity_change",
    "per_suit.Club.other_trade_summaries.item_3.buy_quantity",
    "per_suit.Club.other_trade_summaries.item_3.buy_consideration",
    "per_suit.Club.other_trade_summaries.item_3.sell_quantity",
    "per_suit.Club.other_trade_summaries.item_3.sell_consideration",
    "per_suit.Club.other_trade_summaries.item_3.min_net_quantity_change",
    "per_suit.Club.market_quote.bid.price",
    "per_suit.Club.market_quote.bid.quantity",
    "per_suit.Club.market_quote.ask.price",
    "per_suit.Club.market_quote.ask.quantity",
    "per_suit.Heart.last_price",
    "per_suit.Heart.volume",
    "per_suit.Heart.self_position",
    "per_suit.Heart.known_count",
    "per_suit.Heart.self_trade_summary.buy_quantity",
    "per_suit.Heart.self_trade_summary.buy_consideration",
    "per_suit.Heart.self_trade_summary.sell_quantity",
    "per_suit.Heart.self_trade_summary.sell_consideration",
    "per_suit.Heart.self_trade_summary.min_net_quantity_change",
    "per_suit.Heart.other_trade_summaries.item_0.buy_quantity",
    "per_suit.Heart.other_trade_summaries.item_0.buy_consideration",
    "per_suit.Heart.other_trade_summaries.item_0.sell_quantity",
    "per_suit.Heart.other_trade_summaries.item_0.sell_consideration",
    "per_suit.Heart.other_trade_summaries.item_0.min_net_quantity_change",
    "per_suit.Heart.other_trade_summaries.item_1.buy_quantity",
    "per_suit.Heart.other_trade_summaries.item_1.buy_consideration",
    "per_suit.Heart.other_trade_summaries.item_1.sell_quantity",
    "per_suit.Heart.other_trade_summaries.item_1.sell_consideration",
    "per_suit.Heart.other_trade_summaries.item_1.min_net_quantity_change",
    "per_suit.Heart.other_trade_summaries.item_2.buy_quantity",
    "per_suit.Heart.other_trade_summaries.item_2.buy_consideration",
    "per_suit.Heart.other_trade_summaries.item_2.sell_quantity",
    "per_suit.Heart.other_trade_summaries.item_2.sell_consideration",
    "per_suit.Heart.other_trade_summaries.item_2.min_net_quantity_change",
    "per_suit.Heart.other_trade_summaries.item_3.buy_quantity",
    "per_suit.Heart.other_trade_summaries.item_3.buy_consideration",
    "per_suit.Heart.other_trade_summaries.item_3.sell_quantity",
    "per_suit.Heart.other_trade_summaries.item_3.sell_consideration",
    "per_suit.Heart.other_trade_summaries.item_3.min_net_quantity_change",
    "per_suit.Heart.market_quote.bid.price",
    "per_suit.Heart.market_quote.bid.quantity",
    "per_suit.Heart.market_quote.ask.price",
    "per_suit.Heart.market_quote.ask.quantity",
    "per_suit.Diamond.last_price",
    "per_suit.Diamond.volume",
    "per_suit.Diamond.self_position",
    "per_suit.Diamond.known_count",
    "per_suit.Diamond.self_trade_summary.buy_quantity",
    "per_suit.Diamond.self_trade_summary.buy_consideration",
    "per_suit.Diamond.self_trade_summary.sell_quantity",
    "per_suit.Diamond.self_trade_summary.sell_consideration",
    "per_suit.Diamond.self_trade_summary.min_net_quantity_change",
    "per_suit.Diamond.other_trade_summaries.item_0.buy_quantity",
    "per_suit.Diamond.other_trade_summaries.item_0.buy_consideration",
    "per_suit.Diamond.other_trade_summaries.item_0.sell_quantity",
    "per_suit.Diamond.other_trade_summaries.item_0.sell_consideration",
    "per_suit.Diamond.other_trade_summaries.item_0.min_net_quantity_change",
    "per_suit.Diamond.other_trade_summaries.item_1.buy_quantity",
    "per_suit.Diamond.other_trade_summaries.item_1.buy_consideration",
    "per_suit.Diamond.other_trade_summaries.item_1.sell_quantity",
    "per_suit.Diamond.other_trade_summaries.item_1.sell_consideration",
    "per_suit.Diamond.other_trade_summaries.item_1.min_net_quantity_change",
    "per_suit.Diamond.other_trade_summaries.item_2.buy_quantity",
    "per_suit.Diamond.other_trade_summaries.item_2.buy_consideration",
    "per_suit.Diamond.other_trade_summaries.item_2.sell_quantity",
    "per_suit.Diamond.other_trade_summaries.item_2.sell_consideration",
    "per_suit.Diamond.other_trade_summaries.item_2.min_net_quantity_change",
    "per_suit.Diamond.other_trade_summaries.item_3.buy_quantity",
    "per_suit.Diamond.other_trade_summaries.item_3.buy_consideration",
    "per_suit.Diamond.other_trade_summaries.item_3.sell_quantity",
    "per_suit.Diamond.other_trade_summaries.item_3.sell_consideration",
    "per_suit.Diamond.other_trade_summaries.item_3.min_net_quantity_change",
    "per_suit.Diamond.market_quote.bid.price",
    "per_suit.Diamond.market_quote.bid.quantity",
    "per_suit.Diamond.market_quote.ask.price",
    "per_suit.Diamond.market_quote.ask.quantity",
]
